// Code generated by Kitex v0.6.1. DO NOT EDIT.

package lengthservice

import (
	length "api-gateway/length-service/kitex_gen/length"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return lengthServiceServiceInfo
}

var lengthServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "LengthService"
	handlerType := (*length.LengthService)(nil)
	methods := map[string]kitex.MethodInfo{
		"calculateLength": kitex.NewMethodInfo(calculateLengthHandler, newLengthServiceCalculateLengthArgs, newLengthServiceCalculateLengthResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "length",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func calculateLengthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*length.LengthServiceCalculateLengthArgs)
	realResult := result.(*length.LengthServiceCalculateLengthResult)
	success, err := handler.(length.LengthService).CalculateLength(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLengthServiceCalculateLengthArgs() interface{} {
	return length.NewLengthServiceCalculateLengthArgs()
}

func newLengthServiceCalculateLengthResult() interface{} {
	return length.NewLengthServiceCalculateLengthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CalculateLength(ctx context.Context, req *length.LengthRequest) (r *length.LengthResponse, err error) {
	var _args length.LengthServiceCalculateLengthArgs
	_args.Req = req
	var _result length.LengthServiceCalculateLengthResult
	if err = p.c.Call(ctx, "calculateLength", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
