// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _convertcaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _calculatelengthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reversestringMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _findsubstringMw() []app.HandlerFunc {
	// your code...
	return nil
}
