// Code generated by Kitex v0.6.1. DO NOT EDIT.

package conversionservice

import (
	conversion "api-gateway/conversion-service/kitex_gen/conversion"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ConvertCase(ctx context.Context, req *conversion.ConversionRequest, callOptions ...callopt.Option) (r *conversion.ConversionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConversionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConversionServiceClient struct {
	*kClient
}

func (p *kConversionServiceClient) ConvertCase(ctx context.Context, req *conversion.ConversionRequest, callOptions ...callopt.Option) (r *conversion.ConversionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConvertCase(ctx, req)
}
